### ISSUE TITLE
Instalation corrupted numpy installation somehow

### ISSUE THREAD

**Issue by mihapiha** [stephenhky/PyShortTextCategorization#48]
When I installed your package with pip, all packages that depend on numpy started to fail. My disappointment is immeasurable, and my day is ruined.

**Comment by stephenhky** [comment]
I am sorry to hear that. Would you post the config of your computer, and also the error message? Thanks!

**Comment by stephenhky** [comment]
I have release 1.0.7, with additional instructions when installation fails. Would you try them to see if there are still issues?

**Comment by stephenhky** [comment]
This might solve your problem. After you installed numpy, launch python, and type

```
import numpy as np
print(np.get_include())
```

Then it output a directly. Then in your `~/.bash_profile`, add this line:

```
export CFLAGS="-I <the directory you got> $CFLAGS"
```

**Comment by prokotg** [comment]
Hey there! I had an environment with no numpy installed and installation crashed because of compiler included folders (that is, I had to import numpy at the very beggining of setup.py). I installed numpy, no biggie ,but maybe it should be installed right at the very beginning with pip.main? 

Cheers :)

**Comment by stephenhky** [comment]
@prokotg how do i set it in a way that it install numpy first before running installation for other things?
